[package]
name = "sound-converter-app"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "1", features = [] }

[build-dependencies]
tauri-build = { version = "1", features = [] }
